version: '3.9'

services:
  mongo:
    container_name: yummy-yams
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./api/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
